### ISSUE TITLE
Does not work on my installation

### ISSUE THREAD

**Issue by Teetrinker** [hofff/contao-shariff#10]
I have a Contao 3.4.4 installation.
I renamed the folder "contao-module" to "hofff_shariff" and put it in the system/modules folder.
I put the folder Hofff in the root directory.

I could create a backend module, but it does not show any output at all, not even the title.
There is no error in the log file

**Comment by frontendschlampe** [comment]
If I understand it in the right way, you tried a manual installation?

**Comment by Teetrinker** [comment]
Yes, downloaded the github zip file.

**Comment by Teetrinker** [comment]
I just checked the composer.json and move the folder Hofff to root/src/- but the situation stays the same.

**Comment by frontendschlampe** [comment]
Yes - and that's the problem. As you can read in the `composer.json` https://github.com/hofff/contao-shariff/blob/1.x/composer.json#L23 we have a requirement of `heise/shariff` and when you go to `heise/shariff` https://github.com/heiseonline/shariff-backend-php/blob/master/composer.json#L23-L26 you will see, that they require also some various extensions. That's why the extension is not working with a manual installation. We want to provide a nightly builder on our website in the future but till now we don't find the time to set it up. Until the nightly builder is working you have to install the extension via composer.

**Comment by Teetrinker** [comment]
Thanks a heap for the fast replies!
